 "use client";
import {useEffect,useState} from "react";
import {getJSON,postJSON} from "../lib/api";
import {Activity,BrainCircuit,Database,Gauge,MessageSquare,Play,RefreshCw,Server} from "lucide-react";
import {LineChart,Line,XAxis,YAxis,Tooltip,ResponsiveContainer} from "recharts";

type Model={name:string;size?:string;modified?:string};
type Stats={models:number;runs:number;best_model:string;avg_latency:number};
type Run={model:string;category:string;accuracy:number;latency_ms:number;tokens_per_sec:number;score:number;created_at:string};

export default function Dashboard(){
 const [models,setModels]=useState<Model[]>([]);
 const [stats,setStats]=useState<Stats|null>(null);
 const [runs,setRuns]=useState<Run[]>([]);
 const [model,setModel]=useState("");
 const [prompt,setPrompt]=useState("");
 const [answer,setAnswer]=useState("");
 const [loading,setLoading]=useState(false);
 const [tab,setTab]=useState("Overview");

 async function refresh(){
   try{
    const [m,s,r]=await Promise.all([getJSON<{models:Model[]}>("/models"),getJSON<Stats>("/stats"),getJSON<{runs:Run[]}>("/benchmarks?limit=12")]);
    setModels(m.models); setStats(s); setRuns(r.runs); if(!model&&m.models[0])setModel(m.models[0].name);
   }catch(e){console.error(e)}
 }
 useEffect(()=>{refresh()},[]);
 async function chat(){
   if(!prompt.trim()||!model)return; setLoading(true);setAnswer("");
   try{const x=await postJSON<{answer:string}>("/chat",{model,prompt});setAnswer(x.answer);await refresh()}
   catch(e){setAnswer("Backend/Ollama error. Make sure Ollama and FastAPI are running.")}
   finally{setLoading(false)}
 }
 async function benchmark(){
   setLoading(true);
   try{await postJSON("/benchmark/run",{model:model||undefined,categories:["general","coding","healthcare","banking","legal"]});await refresh()}
   catch(e){alert("Benchmark failed. Check backend and Ollama.")}
   finally{setLoading(false)}
 }
 const chart=runs.slice().reverse().map((r,i)=>({i:i+1,score:r.score,latency:Math.round(r.latency_ms)}));
 return <div className="shell">
  <aside className="side">
   <div className="brand"><BrainCircuit size={19} style={{verticalAlign:"middle"}}/> Offline<span>Bench</span></div>
   <div className="nav">{["Overview","Assistant","Benchmarks","Models","System"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}</button>)}</div>
   <div style={{marginTop:30}} className="muted">LOCAL MODE</div>
   <div className="card" style={{marginTop:8}}><div className="label">Privacy</div><div style={{marginTop:5,fontWeight:700}}>No cloud inference</div><div className="label" style={{marginTop:5}}>Your prompts stay on this machine.</div></div>
  </aside>
  <main className="main">
   <div className="top"><div><div className="eyebrow">Local intelligence laboratory</div><div className="title">Offline AI Assistant + Model Benchmark</div><div className="muted">Chat locally. Measure objectively. Compare models.</div></div><button className="ghost" onClick={refresh}><RefreshCw size={16}/> Refresh</button></div>
   <div className="grid">
    <div className="card"><div className="label"><Server size={14}/> Local models</div><div className="metric">{stats?.models??"—"}</div></div>
    <div className="card"><div className="label"><Activity size={14}/> Benchmark runs</div><div className="metric">{stats?.runs??"—"}</div></div>
    <div className="card"><div className="label"><Gauge size={14}/> Avg latency</div><div className="metric">{stats?`${Math.round(stats.avg_latency)} ms`:"—"}</div></div>
    <div className="card"><div className="label"><Database size={14}/> Best model</div><div className="metric" style={{fontSize:18}}>{stats?.best_model||"—"}</div></div>
   </div>
   {tab==="Assistant"||tab==="Overview"?<div className="layout2">
    <section className="card chat">
      <div className="sectionTitle"><MessageSquare size={18}/> Local Assistant</div>
      <div className="row"><select className="select" value={model} onChange={e=>setModel(e.target.value)}>{models.length?models.map(m=><option key={m.name}>{m.name}</option>):<option>No models</option>}</select></div>
      <div className="chatlog">{answer&&<div className="msg assistant">{answer}</div>} {!answer&&!loading&&<div className="muted">Ask a question. The response is generated by your selected local model.</div>}{loading&&<div className="msg assistant">Running local model…</div>}</div>
      <div className="row"><input className="input" value={prompt} onChange={e=>setPrompt(e.target.value)} onKeyDown={e=>e.key==="Enter"&&chat()} placeholder="Ask your local AI..." /><button className="primary" onClick={chat} disabled={loading}>Send</button></div>
    </section>
    <section className="card">
      <div className="sectionTitle">Benchmark signal</div>
      <div style={{height:270}}><ResponsiveContainer width="100%" height="100%"><LineChart data={chart}><XAxis dataKey="i"/><YAxis/><Tooltip/><Line type="monotone" dataKey="score" strokeWidth={2} dot={false}/></LineChart></ResponsiveContainer></div>
      <div className="actions"><button className="primary" onClick={benchmark} disabled={loading}><Play size={15}/> Run benchmark</button><span className="pill">30–40 questions / category</span></div>
    </section>
   </div>:null}
   {(tab==="Benchmarks"||tab==="Overview")&&<section className="card" style={{marginTop:16}}>
     <div className="top" style={{marginBottom:8}}><div><div className="sectionTitle">Recent benchmark results</div><div className="muted">Measured on your local hardware.</div></div><button className="ghost" onClick={benchmark}>Run now</button></div>
     <table className="table"><thead><tr><th>Model</th><th>Category</th><th>Accuracy</th><th>Latency</th><th>Tok/s</th><th>Score</th></tr></thead><tbody>{runs.map((r,i)=><tr key={i}><td>{r.model}</td><td><span className="pill">{r.category}</span></td><td>{r.accuracy}%</td><td>{Math.round(r.latency_ms)} ms</td><td>{r.tokens_per_sec.toFixed(1)}</td><td><b>{r.score.toFixed(1)}</b>/10</td></tr>)}</tbody></table>
   </section>}
   {tab==="Models"&&<section className="card" style={{marginTop:16}}><div className="sectionTitle">Installed local models</div>{models.map(m=><div key={m.name} style={{padding:"14px 0",borderBottom:"1px solid #202638"}}><b>{m.name}</b><div className="muted">{m.size||"local"} · Ollama</div></div>)}</section>}
   {tab==="System"&&<section className="card" style={{marginTop:16}}><div className="sectionTitle">System architecture</div><pre className="muted">Browser → Next.js → FastAPI → Ollama → Local LLM{"\n"}                           ↓{"\n"}                       SQLite benchmarks</pre></section>}
  </main>
 </div>
}
